# Enhanced Database MCP Server - Simplified SSP Tool Definitions
# YAML-based tool definitions for SSP-only architecture

metadata:
  name: "SSP Database MCP Tools"
  version: "3.0.0"
  description: "Simplified 3-tool architecture - All operations via SSP API endpoints"
  created_date: "2025-08-19"
  architecture: "SSP-First"

# =============================================================================
# CORE SSP MCP TOOL DEFINITIONS (3 Tools Only)
# =============================================================================

tools:
  ssp_portal_interaction:
    name: "ssp_portal_interaction"
    description: "Primary SSP portal API interaction tool - handles all operations through SSP endpoints including natural language processing"
    category: "ssp_operations"
    requires_confirmation: false
    implementation_class: "EnhancedMCPTools"
    implementation_method: "ssp_portal_interaction"
    input_schema:
      type: "object"
      properties:
        operation_type:
          type: "string"
          enum: ["natural_language_request", "api_call", "workflow_execution", "performance_analysis", "backup_operation", "query_execution"]
          description: "Type of SSP operation to perform"
        endpoint:
          type: "string"
          description: "SSP API endpoint path (e.g., /api/v1/databases/query)"
        request_method:
          type: "string"
          enum: ["GET", "POST", "PUT", "DELETE", "PATCH"]
          default: "GET"
          description: "HTTP method for SSP API call"
        parameters:
          type: "object"
          description: "Parameters for SSP API call or natural language input"
          properties:
            user_input:
              type: "string"
              description: "Natural language request (for operation_type: natural_language_request)"
            filters:
              type: "object"
              description: "Query filters for SSP API"
            targets:
              type: "array"
              items:
                type: "string"
              description: "Target resources (databases, tables, etc.)"
            options:
              type: "object"
              description: "Additional operation options"
        portal_id:
          type: "string"
          default: "default_ssp"
          description: "SSP portal identifier"
        session_id:
          type: "string"
          default: "default_session"
          description: "Session identifier for tracking"
      required: ["operation_type"]
    examples:
      - input:
          operation_type: "natural_language_request"
          parameters:
            user_input: "Show me all production databases"
          session_id: "user_123"
        description: "Natural language query via SSP API"
      - input:
          operation_type: "api_call"
          endpoint: "/api/v1/databases/list"
          request_method: "GET"
          parameters:
            filters:
              environment: "production"
        description: "Direct SSP API call"

  inventory_metadata_interaction:
    name: "inventory_metadata_interaction"
    description: "Database and resource inventory management via SSP APIs - handles all metadata operations through SSP endpoints only"
    category: "ssp_inventory"
    requires_confirmation: false
    implementation_class: "EnhancedMCPTools"
    implementation_method: "inventory_metadata_interaction"
    input_schema:
      type: "object"
      properties:
        inventory_action:
          type: "string"
          enum: ["list", "detail", "search", "health_check", "metadata_fetch", "schema_analyze"]
          default: "list"
          description: "Inventory operation to perform via SSP API"
        resource_types:
          type: "array"
          items:
            type: "string"
            enum: ["databases", "tables", "schemas", "indexes", "views", "procedures"]
          default: ["databases"]
          description: "Types of resources to query via SSP"
        filters:
          type: "object"
          properties:
            environment:
              type: "string"
              enum: ["development", "staging", "production", "all"]
              default: "all"
            health_status:
              type: "string"
              enum: ["healthy", "warning", "critical", "all"]
              default: "all"
            portal_specific:
              type: "object"
              description: "Portal-specific filter parameters"
        include_metadata:
          type: "boolean"
          default: true
          description: "Include detailed metadata in SSP API response"
        include_health_status:
          type: "boolean"
          default: true
          description: "Include health status in SSP API response"
        portal_ids:
          type: "array"
          items:
            type: "string"
          description: "Specific SSP portal IDs to query"
        ai_insights:
          type: "boolean"
          default: false
          description: "Generate AI insights from inventory data"
      required: ["inventory_action"]
    examples:
      - input:
          inventory_action: "list"
          resource_types: ["databases"]
          filters:
            environment: "production"
            health_status: "critical"
          ai_insights: true
        description: "List critical production databases with AI insights"
      - input:
          inventory_action: "metadata_fetch"
          resource_types: ["tables", "schemas"]
          filters:
            portal_specific:
              database_name: "user_data"
        description: "Fetch metadata for specific database via SSP"

  unified_response:
    name: "unified_response"
    description: "Consolidated response aggregation and AI-powered insights combining multiple SSP operations"
    category: "ssp_aggregation"
    requires_confirmation: false
    implementation_class: "EnhancedMCPTools"
    implementation_method: "unified_response"
    input_schema:
      type: "object"
      properties:
        response_type:
          type: "string"
          enum: ["summary", "detailed", "analysis", "recommendations", "workflow_plan"]
          default: "summary"
          description: "Type of unified response to generate"
        session_id:
          type: "string"
          default: "default_session"
          description: "Session to aggregate responses from"
        include_recommendations:
          type: "boolean"
          default: true
          description: "Include AI-powered recommendations"
        include_workflow_suggestions:
          type: "boolean"
          default: true
          description: "Include workflow suggestions based on SSP operations"
        context_operations:
          type: "array"
          items:
            type: "string"
          description: "Specific operations to include in unified response"
        aggregation_options:
          type: "object"
          properties:
            time_window:
              type: "string"
              enum: ["last_hour", "last_day", "session_only", "all"]
              default: "session_only"
            priority_filter:
              type: "string"
              enum: ["high", "medium", "low", "all"]
              default: "all"
            include_metrics:
              type: "boolean"
              default: true
      required: ["response_type"]
    examples:
      - input:
          response_type: "analysis"
          session_id: "user_123"
          include_recommendations: true
          aggregation_options:
            time_window: "session_only"
            include_metrics: true
        description: "Generate analysis of all SSP operations in session"
      - input:
          response_type: "workflow_plan"
          context_operations: ["database_query", "performance_analysis"]
          include_workflow_suggestions: true
        description: "Create workflow plan based on recent SSP operations"

# =============================================================================
# SSP TOOL CONFIGURATION SETTINGS
# =============================================================================

tool_settings:
  default_timeout_seconds: 300
  max_concurrent_tools: 3
  enable_caching: true
  cache_ttl_seconds: 3600
  ssp_primary: true
  
  categories:
    ssp_operations:
      description: "Primary SSP portal operations and natural language processing"
      color: "#2196F3"
      icon: "🔌"
      priority: 1
    ssp_inventory:
      description: "Inventory and metadata operations via SSP APIs"
      color: "#FF9800"
      icon: "📊"
      priority: 2
    ssp_aggregation:
      description: "Unified response aggregation and AI insights"
      color: "#4CAF50"
      icon: "🎯"
      priority: 3

  validation:
    required_fields_validation: true
    schema_validation: true
    type_checking: true
    ssp_endpoint_validation: true

  monitoring:
    track_usage: true
    log_performance: true
    alert_on_errors: true
    metrics_collection: true
    ssp_api_metrics: true

# =============================================================================
# SSP INTEGRATION CONFIGURATION
# =============================================================================

integration:
  ssp_primary_mode: true
  langchain_tools: true
  langgraph_workflows: true
  gemini_llm: true
  portal_manager: true
  intent_classifier: true
  conversation_flow: true
  
  ssp_endpoints:
    base_url: "${SSP_BASE_URL}"
    api_version: "v1"
    authentication:
      type: "bearer_token"
      token: "${SSP_API_TOKEN}"
    
    core_endpoints:
      databases: "/api/v1/databases"
      operations: "/api/v1/operations"
      analytics: "/api/v1/analytics"
      metadata: "/api/v1/metadata"
      health: "/api/v1/health"

# =============================================================================
# ERROR HANDLING
# =============================================================================

error_handling:
  retry_attempts: 3
  retry_delay_seconds: 5
  fallback_behavior: "graceful_degradation"
  error_reporting: true
  user_friendly_messages: true
  ssp_specific_errors: true
